version: '2'
services:
    database:
        image: davisruk/cmdb_db
        container_name: ${ENV_NAME}_cmdb_db
        volumes:
            - "~/$ENV_NAME/data:/var/lib/mysql"
    web:
        image: davisruk/cmdb_ui
        container_name: ${ENV_NAME}_cmdb_ui
        environment:
            - EXT_HOSTNAME=${EXT_HOSTNAME}
            - SVC_EXT_PORT=${SVC_EXT_PORT}
            - UI_EXT_PORT=${UI_EXT_PORT}
        ports:
            - "${UI_EXT_PORT}:3000"
        links:
            - data_service
    data_service:
        depends_on:
            - database
        environment:
            - APP_OPTS=--spring.datasource.url=jdbc:mysql://${ENV_NAME}_cmdb_db:3306/cmdbnode --cors.origin.hosts=http://${EXT_HOSTNAME}:${UI_EXT_PORT},http://${EXT_HOSTNAME}:${SVC_EXT_PORT},http://${ENV_NAME}_cmdb_ui:3000
        image: davisruk/cmdb_backend
        container_name: ${ENV_NAME}_cmdb_backend
        ports:
            - "${SVC_EXT_PORT}:8080"
        links:
            - database
